import dev.kikugie.stonecutter.build.config.ReplacementContainer

// Generated from the Mojang 1.16.5 obfuscation map composed with MCPConfig 1.16.5.
// Forge <= 1.16 ships MCP class names with official member names, so only class and
// package names are rewritten. Every rule pins the characters around the token, which
// makes the set order-independent and exactly reversible.
internal fun ReplacementContainer.RegexReplacementSpec.mcpClassNames1_16() {

	// fully qualified names
	replace("\\bcom\\.mojang\\.blaze3d\\.vertex\\.PoseStack\\b", "com.mojang.blaze3d.matrix.MatrixStack",
		"\\bcom\\.mojang\\.blaze3d\\.matrix\\.MatrixStack\\b", "com.mojang.blaze3d.vertex.PoseStack")
	replace("\\bcom\\.mojang\\.blaze3d\\.vertex\\.VertexConsumer\\b", "com.mojang.blaze3d.vertex.IVertexBuilder",
		"\\bcom\\.mojang\\.blaze3d\\.vertex\\.IVertexBuilder\\b", "com.mojang.blaze3d.vertex.VertexConsumer")
	replace("\\bnet\\.minecraft\\.world\\.level\\.block\\.state\\.BlockBehaviour\\b", "net.minecraft.block.AbstractBlock",
		"\\bnet\\.minecraft\\.block\\.AbstractBlock\\b", "net.minecraft.world.level.block.state.BlockBehaviour")
	replace("\\bnet\\.minecraft\\.world\\.level\\.block\\.SignBlock\\b", "net.minecraft.block.AbstractSignBlock",
		"\\bnet\\.minecraft\\.block\\.AbstractSignBlock\\b", "net.minecraft.world.level.block.SignBlock")
	replace("\\bnet\\.minecraft\\.world\\.level\\.block\\.BedBlock\\b", "net.minecraft.block.BedBlock",
		"\\bnet\\.minecraft\\.block\\.BedBlock\\b", "net.minecraft.world.level.block.BedBlock")
	replace("\\bnet\\.minecraft\\.world\\.level\\.block\\.Block\\b", "net.minecraft.block.Block",
		"\\bnet\\.minecraft\\.block\\.Block\\b", "net.minecraft.world.level.block.Block")
	replace("\\bnet\\.minecraft\\.world\\.level\\.block\\.RenderShape\\b", "net.minecraft.block.BlockRenderType",
		"\\bnet\\.minecraft\\.block\\.BlockRenderType\\b", "net.minecraft.world.level.block.RenderShape")
	replace("\\bnet\\.minecraft\\.world\\.level\\.block\\.state\\.BlockState\\b", "net.minecraft.block.BlockState",
		"\\bnet\\.minecraft\\.block\\.BlockState\\b", "net.minecraft.world.level.block.state.BlockState")
	replace("\\bnet\\.minecraft\\.world\\.level\\.block\\.Blocks\\b", "net.minecraft.block.Blocks",
		"\\bnet\\.minecraft\\.block\\.Blocks\\b", "net.minecraft.world.level.block.Blocks")
	replace("\\bnet\\.minecraft\\.world\\.level\\.block\\.ChestBlock\\b", "net.minecraft.block.ChestBlock",
		"\\bnet\\.minecraft\\.block\\.ChestBlock\\b", "net.minecraft.world.level.block.ChestBlock")
	replace("\\bnet\\.minecraft\\.world\\.level\\.block\\.ShulkerBoxBlock\\b", "net.minecraft.block.ShulkerBoxBlock",
		"\\bnet\\.minecraft\\.block\\.ShulkerBoxBlock\\b", "net.minecraft.world.level.block.ShulkerBoxBlock")
	replace("\\bnet\\.minecraft\\.world\\.level\\.block\\.StandingSignBlock\\b", "net.minecraft.block.StandingSignBlock",
		"\\bnet\\.minecraft\\.block\\.StandingSignBlock\\b", "net.minecraft.world.level.block.StandingSignBlock")
	replace("\\bnet\\.minecraft\\.world\\.level\\.block\\.WallSignBlock\\b", "net.minecraft.block.WallSignBlock",
		"\\bnet\\.minecraft\\.block\\.WallSignBlock\\b", "net.minecraft.world.level.block.WallSignBlock")
	replace("\\bnet\\.minecraft\\.client\\.Option\\b", "net.minecraft.client.AbstractOption",
		"\\bnet\\.minecraft\\.client\\.AbstractOption\\b", "net.minecraft.client.Option")
	replace("\\bnet\\.minecraft\\.client\\.Options\\b", "net.minecraft.client.GameSettings",
		"\\bnet\\.minecraft\\.client\\.GameSettings\\b", "net.minecraft.client.Options")
	replace("\\bnet\\.minecraft\\.network\\.chat\\.CommonComponents\\b", "net.minecraft.client.gui.DialogTexts",
		"\\bnet\\.minecraft\\.client\\.gui\\.DialogTexts\\b", "net.minecraft.network.chat.CommonComponents")
	replace("\\bnet\\.minecraft\\.client\\.gui\\.Font\\b", "net.minecraft.client.gui.FontRenderer",
		"\\bnet\\.minecraft\\.client\\.gui\\.FontRenderer\\b", "net.minecraft.client.gui.Font")
	replace("\\bnet\\.minecraft\\.client\\.gui\\.components\\.events\\.GuiEventListener\\b", "net.minecraft.client.gui.IGuiEventListener",
		"\\bnet\\.minecraft\\.client\\.gui\\.IGuiEventListener\\b", "net.minecraft.client.gui.components.events.GuiEventListener")
	replace("\\bnet\\.minecraft\\.client\\.gui\\.screens\\.worldselection\\.WorldPreset\\b", "net.minecraft.client.gui.screen.BiomeGeneratorTypeScreens",
		"\\bnet\\.minecraft\\.client\\.gui\\.screen\\.BiomeGeneratorTypeScreens\\b", "net.minecraft.client.gui.screens.worldselection.WorldPreset")
	replace("\\bnet\\.minecraft\\.client\\.gui\\.screens\\.inventory\\.SignEditScreen\\b", "net.minecraft.client.gui.screen.EditSignScreen",
		"\\bnet\\.minecraft\\.client\\.gui\\.screen\\.EditSignScreen\\b", "net.minecraft.client.gui.screens.inventory.SignEditScreen")
	replace("\\bnet\\.minecraft\\.client\\.gui\\.screens\\.Screen\\b", "net.minecraft.client.gui.screen.Screen",
		"\\bnet\\.minecraft\\.client\\.gui\\.screen\\.Screen\\b", "net.minecraft.client.gui.screens.Screen")
	replace("\\bnet\\.minecraft\\.client\\.gui\\.screens\\.OptionsSubScreen\\b", "net.minecraft.client.gui.screen.SettingsScreen",
		"\\bnet\\.minecraft\\.client\\.gui\\.screen\\.SettingsScreen\\b", "net.minecraft.client.gui.screens.OptionsSubScreen")
	replace("\\bnet\\.minecraft\\.client\\.gui\\.screens\\.VideoSettingsScreen\\b", "net.minecraft.client.gui.screen.VideoSettingsScreen",
		"\\bnet\\.minecraft\\.client\\.gui\\.screen\\.VideoSettingsScreen\\b", "net.minecraft.client.gui.screens.VideoSettingsScreen")
	replace("\\bnet\\.minecraft\\.client\\.gui\\.components\\.AbstractWidget\\b", "net.minecraft.client.gui.widget.Widget",
		"\\bnet\\.minecraft\\.client\\.gui\\.widget\\.Widget\\b", "net.minecraft.client.gui.components.AbstractWidget")
	replace("\\bnet\\.minecraft\\.client\\.gui\\.components\\.Button\\b", "net.minecraft.client.gui.widget.button.Button",
		"\\bnet\\.minecraft\\.client\\.gui\\.widget\\.button\\.Button\\b", "net.minecraft.client.gui.components.Button")
	replace("\\bnet\\.minecraft\\.client\\.gui\\.components\\.ContainerObjectSelectionList\\b", "net.minecraft.client.gui.widget.list.AbstractOptionList",
		"\\bnet\\.minecraft\\.client\\.gui\\.widget\\.list\\.AbstractOptionList\\b", "net.minecraft.client.gui.components.ContainerObjectSelectionList")
	replace("\\bnet\\.minecraft\\.client\\.gui\\.components\\.OptionsList\\b", "net.minecraft.client.gui.widget.list.OptionsRowList",
		"\\bnet\\.minecraft\\.client\\.gui\\.widget\\.list\\.OptionsRowList\\b", "net.minecraft.client.gui.components.OptionsList")
	replace("\\bnet\\.minecraft\\.client\\.renderer\\.Sheets\\b", "net.minecraft.client.renderer.Atlases",
		"\\bnet\\.minecraft\\.client\\.renderer\\.Atlases\\b", "net.minecraft.client.renderer.Sheets")
	replace("\\bnet\\.minecraft\\.client\\.renderer\\.MultiBufferSource\\b", "net.minecraft.client.renderer.IRenderTypeBuffer",
		"\\bnet\\.minecraft\\.client\\.renderer\\.IRenderTypeBuffer\\b", "net.minecraft.client.renderer.MultiBufferSource")
	replace("\\bcom\\.mojang\\.blaze3d\\.platform\\.Lighting\\b", "net.minecraft.client.renderer.RenderHelper",
		"\\bnet\\.minecraft\\.client\\.renderer\\.RenderHelper\\b", "com.mojang.blaze3d.platform.Lighting")
	replace("\\bnet\\.minecraft\\.client\\.renderer\\.ItemBlockRenderTypes\\b", "net.minecraft.client.renderer.RenderTypeLookup",
		"\\bnet\\.minecraft\\.client\\.renderer\\.RenderTypeLookup\\b", "net.minecraft.client.renderer.ItemBlockRenderTypes")
	replace("\\bnet\\.minecraft\\.client\\.renderer\\.LevelRenderer\\b", "net.minecraft.client.renderer.WorldRenderer",
		"\\bnet\\.minecraft\\.client\\.renderer\\.WorldRenderer\\b", "net.minecraft.client.renderer.LevelRenderer")
	replace("\\bnet\\.minecraft\\.client\\.renderer\\.block\\.model\\.BakedQuad\\b", "net.minecraft.client.renderer.model.BakedQuad",
		"\\bnet\\.minecraft\\.client\\.renderer\\.model\\.BakedQuad\\b", "net.minecraft.client.renderer.block.model.BakedQuad")
	replace("\\bnet\\.minecraft\\.client\\.resources\\.model\\.BakedModel\\b", "net.minecraft.client.renderer.model.IBakedModel",
		"\\bnet\\.minecraft\\.client\\.renderer\\.model\\.IBakedModel\\b", "net.minecraft.client.resources.model.BakedModel")
	replace("\\bnet\\.minecraft\\.client\\.resources\\.model\\.ModelState\\b", "net.minecraft.client.renderer.model.IModelTransform",
		"\\bnet\\.minecraft\\.client\\.renderer\\.model\\.IModelTransform\\b", "net.minecraft.client.resources.model.ModelState")
	replace("\\bnet\\.minecraft\\.client\\.resources\\.model\\.UnbakedModel\\b", "net.minecraft.client.renderer.model.IUnbakedModel",
		"\\bnet\\.minecraft\\.client\\.renderer\\.model\\.IUnbakedModel\\b", "net.minecraft.client.resources.model.UnbakedModel")
	replace("\\bnet\\.minecraft\\.client\\.renderer\\.block\\.model\\.ItemTransforms\\b", "net.minecraft.client.renderer.model.ItemCameraTransforms",
		"\\bnet\\.minecraft\\.client\\.renderer\\.model\\.ItemCameraTransforms\\b", "net.minecraft.client.renderer.block.model.ItemTransforms")
	replace("\\bnet\\.minecraft\\.client\\.renderer\\.block\\.model\\.ItemOverride\\b", "net.minecraft.client.renderer.model.ItemOverride",
		"\\bnet\\.minecraft\\.client\\.renderer\\.model\\.ItemOverride\\b", "net.minecraft.client.renderer.block.model.ItemOverride")
	replace("\\bnet\\.minecraft\\.client\\.renderer\\.block\\.model\\.ItemOverrides\\b", "net.minecraft.client.renderer.model.ItemOverrideList",
		"\\bnet\\.minecraft\\.client\\.renderer\\.model\\.ItemOverrideList\\b", "net.minecraft.client.renderer.block.model.ItemOverrides")
	replace("\\bnet\\.minecraft\\.client\\.resources\\.model\\.ModelBakery\\b", "net.minecraft.client.renderer.model.ModelBakery",
		"\\bnet\\.minecraft\\.client\\.renderer\\.model\\.ModelBakery\\b", "net.minecraft.client.resources.model.ModelBakery")
	replace("\\bnet\\.minecraft\\.client\\.resources\\.model\\.ModelManager\\b", "net.minecraft.client.renderer.model.ModelManager",
		"\\bnet\\.minecraft\\.client\\.renderer\\.model\\.ModelManager\\b", "net.minecraft.client.resources.model.ModelManager")
	replace("\\bnet\\.minecraft\\.client\\.resources\\.model\\.ModelResourceLocation\\b", "net.minecraft.client.renderer.model.ModelResourceLocation",
		"\\bnet\\.minecraft\\.client\\.renderer\\.model\\.ModelResourceLocation\\b", "net.minecraft.client.resources.model.ModelResourceLocation")
	replace("\\bnet\\.minecraft\\.client\\.resources\\.model\\.BlockModelRotation\\b", "net.minecraft.client.renderer.model.ModelRotation",
		"\\bnet\\.minecraft\\.client\\.renderer\\.model\\.ModelRotation\\b", "net.minecraft.client.resources.model.BlockModelRotation")
	replace("\\bnet\\.minecraft\\.client\\.resources\\.model\\.Material\\b", "net.minecraft.client.renderer.model.RenderMaterial",
		"\\bnet\\.minecraft\\.client\\.renderer\\.model\\.RenderMaterial\\b", "net.minecraft.client.resources.model.Material")
	replace("\\bcom\\.mojang\\.blaze3d\\.platform\\.NativeImage\\b", "net.minecraft.client.renderer.texture.NativeImage",
		"\\bnet\\.minecraft\\.client\\.renderer\\.texture\\.NativeImage\\b", "com.mojang.blaze3d.platform.NativeImage")
	replace("\\bnet\\.minecraft\\.client\\.renderer\\.BlockEntityWithoutLevelRenderer\\b", "net.minecraft.client.renderer.tileentity.ItemStackTileEntityRenderer",
		"\\bnet\\.minecraft\\.client\\.renderer\\.tileentity\\.ItemStackTileEntityRenderer\\b", "net.minecraft.client.renderer.BlockEntityWithoutLevelRenderer")
	replace("\\bnet\\.minecraft\\.client\\.renderer\\.blockentity\\.SignRenderer\\b", "net.minecraft.client.renderer.tileentity.SignTileEntityRenderer",
		"\\bnet\\.minecraft\\.client\\.renderer\\.tileentity\\.SignTileEntityRenderer\\b", "net.minecraft.client.renderer.blockentity.SignRenderer")
	replace("\\bnet\\.minecraft\\.client\\.renderer\\.blockentity\\.BlockEntityRenderer\\b", "net.minecraft.client.renderer.tileentity.TileEntityRenderer",
		"\\bnet\\.minecraft\\.client\\.renderer\\.tileentity\\.TileEntityRenderer\\b", "net.minecraft.client.renderer.blockentity.BlockEntityRenderer")
	replace("\\bnet\\.minecraft\\.client\\.renderer\\.blockentity\\.BlockEntityRenderDispatcher\\b", "net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher",
		"\\bnet\\.minecraft\\.client\\.renderer\\.tileentity\\.TileEntityRendererDispatcher\\b", "net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher")
	replace("\\bnet\\.minecraft\\.client\\.resources\\.language\\.I18n\\b", "net.minecraft.client.resources.I18n",
		"\\bnet\\.minecraft\\.client\\.resources\\.I18n\\b", "net.minecraft.client.resources.language.I18n")
	replace("\\bnet\\.minecraft\\.client\\.multiplayer\\.ClientLevel\\b", "net.minecraft.client.world.ClientWorld",
		"\\bnet\\.minecraft\\.client\\.world\\.ClientWorld\\b", "net.minecraft.client.multiplayer.ClientLevel")
	replace("\\bnet\\.minecraft\\.world\\.item\\.BlockItem\\b", "net.minecraft.item.BlockItem",
		"\\bnet\\.minecraft\\.item\\.BlockItem\\b", "net.minecraft.world.item.BlockItem")
	replace("\\bnet\\.minecraft\\.world\\.item\\.DyeColor\\b", "net.minecraft.item.DyeColor",
		"\\bnet\\.minecraft\\.item\\.DyeColor\\b", "net.minecraft.world.item.DyeColor")
	replace("\\bnet\\.minecraft\\.world\\.item\\.Item\\b", "net.minecraft.item.Item",
		"\\bnet\\.minecraft\\.item\\.Item\\b", "net.minecraft.world.item.Item")
	replace("\\bnet\\.minecraft\\.client\\.renderer\\.item\\.ItemProperties\\b", "net.minecraft.item.ItemModelsProperties",
		"\\bnet\\.minecraft\\.item\\.ItemModelsProperties\\b", "net.minecraft.client.renderer.item.ItemProperties")
	replace("\\bnet\\.minecraft\\.world\\.item\\.ItemStack\\b", "net.minecraft.item.ItemStack",
		"\\bnet\\.minecraft\\.item\\.ItemStack\\b", "net.minecraft.world.item.ItemStack")
	replace("\\bnet\\.minecraft\\.nbt\\.CompoundTag\\b", "net.minecraft.nbt.CompoundNBT",
		"\\bnet\\.minecraft\\.nbt\\.CompoundNBT\\b", "net.minecraft.nbt.CompoundTag")
	replace("\\bnet\\.minecraft\\.server\\.packs\\.resources\\.FallbackResourceManager\\b", "net.minecraft.resources.FallbackResourceManager",
		"\\bnet\\.minecraft\\.resources\\.FallbackResourceManager\\b", "net.minecraft.server.packs.resources.FallbackResourceManager")
	replace("\\bnet\\.minecraft\\.server\\.packs\\.resources\\.ReloadInstance\\b", "net.minecraft.resources.IAsyncReloader",
		"\\bnet\\.minecraft\\.resources\\.IAsyncReloader\\b", "net.minecraft.server.packs.resources.ReloadInstance")
	replace("\\bnet\\.minecraft\\.server\\.packs\\.resources\\.PreparableReloadListener\\b", "net.minecraft.resources.IFutureReloadListener",
		"\\bnet\\.minecraft\\.resources\\.IFutureReloadListener\\b", "net.minecraft.server.packs.resources.PreparableReloadListener")
	replace("\\bnet\\.minecraft\\.server\\.packs\\.repository\\.PackSource\\b", "net.minecraft.resources.IPackNameDecorator",
		"\\bnet\\.minecraft\\.resources\\.IPackNameDecorator\\b", "net.minecraft.server.packs.repository.PackSource")
	replace("\\bnet\\.minecraft\\.server\\.packs\\.resources\\.ResourceManager\\b", "net.minecraft.resources.IResourceManager",
		"\\bnet\\.minecraft\\.resources\\.IResourceManager\\b", "net.minecraft.server.packs.resources.ResourceManager")
	replace("\\bnet\\.minecraft\\.server\\.packs\\.PackResources\\b", "net.minecraft.resources.IResourcePack",
		"\\bnet\\.minecraft\\.resources\\.IResourcePack\\b", "net.minecraft.server.packs.PackResources")
	replace("\\bnet\\.minecraft\\.server\\.packs\\.PackType\\b", "net.minecraft.resources.ResourcePackType",
		"\\bnet\\.minecraft\\.resources\\.ResourcePackType\\b", "net.minecraft.server.packs.PackType")
	replace("\\bnet\\.minecraft\\.server\\.packs\\.resources\\.SimpleReloadableResourceManager\\b", "net.minecraft.resources.SimpleReloadableResourceManager",
		"\\bnet\\.minecraft\\.resources\\.SimpleReloadableResourceManager\\b", "net.minecraft.server.packs.resources.SimpleReloadableResourceManager")
	replace("\\bnet\\.minecraft\\.server\\.packs\\.VanillaPackResources\\b", "net.minecraft.resources.VanillaPack",
		"\\bnet\\.minecraft\\.resources\\.VanillaPack\\b", "net.minecraft.server.packs.VanillaPackResources")
	replace("\\bnet\\.minecraft\\.server\\.packs\\.metadata\\.MetadataSectionSerializer\\b", "net.minecraft.resources.data.IMetadataSectionSerializer",
		"\\bnet\\.minecraft\\.resources\\.data\\.IMetadataSectionSerializer\\b", "net.minecraft.server.packs.metadata.MetadataSectionSerializer")
	replace("\\bnet\\.minecraft\\.server\\.packs\\.metadata\\.pack\\.PackMetadataSection\\b", "net.minecraft.resources.data.PackMetadataSection",
		"\\bnet\\.minecraft\\.resources\\.data\\.PackMetadataSection\\b", "net.minecraft.server.packs.metadata.pack.PackMetadataSection")
	replace("\\bnet\\.minecraft\\.world\\.level\\.block\\.state\\.StateDefinition\\b", "net.minecraft.state.StateContainer",
		"\\bnet\\.minecraft\\.state\\.StateContainer\\b", "net.minecraft.world.level.block.state.StateDefinition")
	replace("\\bnet\\.minecraft\\.world\\.level\\.block\\.state\\.properties\\.BedPart\\b", "net.minecraft.state.properties.BedPart",
		"\\bnet\\.minecraft\\.state\\.properties\\.BedPart\\b", "net.minecraft.world.level.block.state.properties.BedPart")
	replace("\\bnet\\.minecraft\\.world\\.level\\.block\\.state\\.properties\\.BlockStateProperties\\b", "net.minecraft.state.properties.BlockStateProperties",
		"\\bnet\\.minecraft\\.state\\.properties\\.BlockStateProperties\\b", "net.minecraft.world.level.block.state.properties.BlockStateProperties")
	replace("\\bnet\\.minecraft\\.world\\.level\\.block\\.state\\.properties\\.ChestType\\b", "net.minecraft.state.properties.ChestType",
		"\\bnet\\.minecraft\\.state\\.properties\\.ChestType\\b", "net.minecraft.world.level.block.state.properties.ChestType")
	replace("\\bnet\\.minecraft\\.world\\.level\\.block\\.entity\\.BellBlockEntity\\b", "net.minecraft.tileentity.BellTileEntity",
		"\\bnet\\.minecraft\\.tileentity\\.BellTileEntity\\b", "net.minecraft.world.level.block.entity.BellBlockEntity")
	replace("\\bnet\\.minecraft\\.world\\.level\\.block\\.entity\\.ChestBlockEntity\\b", "net.minecraft.tileentity.ChestTileEntity",
		"\\bnet\\.minecraft\\.tileentity\\.ChestTileEntity\\b", "net.minecraft.world.level.block.entity.ChestBlockEntity")
	replace("\\bnet\\.minecraft\\.world\\.level\\.block\\.entity\\.EnderChestBlockEntity\\b", "net.minecraft.tileentity.EnderChestTileEntity",
		"\\bnet\\.minecraft\\.tileentity\\.EnderChestTileEntity\\b", "net.minecraft.world.level.block.entity.EnderChestBlockEntity")
	replace("\\bnet\\.minecraft\\.world\\.level\\.block\\.entity\\.LidBlockEntity\\b", "net.minecraft.tileentity.IChestLid",
		"\\bnet\\.minecraft\\.tileentity\\.IChestLid\\b", "net.minecraft.world.level.block.entity.LidBlockEntity")
	replace("\\bnet\\.minecraft\\.world\\.level\\.block\\.entity\\.ShulkerBoxBlockEntity\\b", "net.minecraft.tileentity.ShulkerBoxTileEntity",
		"\\bnet\\.minecraft\\.tileentity\\.ShulkerBoxTileEntity\\b", "net.minecraft.world.level.block.entity.ShulkerBoxBlockEntity")
	replace("\\bnet\\.minecraft\\.world\\.level\\.block\\.entity\\.SignBlockEntity\\b", "net.minecraft.tileentity.SignTileEntity",
		"\\bnet\\.minecraft\\.tileentity\\.SignTileEntity\\b", "net.minecraft.world.level.block.entity.SignBlockEntity")
	replace("\\bnet\\.minecraft\\.world\\.level\\.block\\.entity\\.BlockEntity\\b", "net.minecraft.tileentity.TileEntity",
		"\\bnet\\.minecraft\\.tileentity\\.TileEntity\\b", "net.minecraft.world.level.block.entity.BlockEntity")
	replace("\\bnet\\.minecraft\\.world\\.level\\.block\\.entity\\.BlockEntityType\\b", "net.minecraft.tileentity.TileEntityType",
		"\\bnet\\.minecraft\\.tileentity\\.TileEntityType\\b", "net.minecraft.world.level.block.entity.BlockEntityType")
	replace("\\bnet\\.minecraft\\.core\\.Direction\\b", "net.minecraft.util.Direction",
		"\\bnet\\.minecraft\\.util\\.Direction\\b", "net.minecraft.core.Direction")
	replace("\\bnet\\.minecraft\\.util\\.FormattedCharSequence\\b", "net.minecraft.util.IReorderingProcessor",
		"\\bnet\\.minecraft\\.util\\.IReorderingProcessor\\b", "net.minecraft.util.FormattedCharSequence")
	replace("\\bnet\\.minecraft\\.resources\\.ResourceKey\\b", "net.minecraft.util.RegistryKey",
		"\\bnet\\.minecraft\\.util\\.RegistryKey\\b", "net.minecraft.resources.ResourceKey")
	replace("\\bnet\\.minecraft\\.resources\\.ResourceLocation\\b", "net.minecraft.util.ResourceLocation",
		"\\bnet\\.minecraft\\.util\\.ResourceLocation\\b", "net.minecraft.resources.ResourceLocation")
	replace("\\bnet\\.minecraft\\.SharedConstants\\b", "net.minecraft.util.SharedConstants",
		"\\bnet\\.minecraft\\.util\\.SharedConstants\\b", "net.minecraft.SharedConstants")
	replace("\\bnet\\.minecraft\\.world\\.level\\.DataPackConfig\\b", "net.minecraft.util.datafix.codec.DatapackCodec",
		"\\bnet\\.minecraft\\.util\\.datafix\\.codec\\.DatapackCodec\\b", "net.minecraft.world.level.DataPackConfig")
	replace("\\bnet\\.minecraft\\.core\\.BlockPos\\b", "net.minecraft.util.math.BlockPos",
		"\\bnet\\.minecraft\\.util\\.math\\.BlockPos\\b", "net.minecraft.core.BlockPos")
	replace("\\bnet\\.minecraft\\.util\\.Mth\\b", "net.minecraft.util.math.MathHelper",
		"\\bnet\\.minecraft\\.util\\.math\\.MathHelper\\b", "net.minecraft.util.Mth")
	replace("\\bnet\\.minecraft\\.core\\.SectionPos\\b", "net.minecraft.util.math.SectionPos",
		"\\bnet\\.minecraft\\.util\\.math\\.SectionPos\\b", "net.minecraft.core.SectionPos")
	replace("\\bcom\\.mojang\\.math\\.Quaternion\\b", "net.minecraft.util.math.vector.Quaternion",
		"\\bnet\\.minecraft\\.util\\.math\\.vector\\.Quaternion\\b", "com.mojang.math.Quaternion")
	replace("\\bnet\\.minecraft\\.world\\.phys\\.Vec3\\b", "net.minecraft.util.math.vector.Vector3d",
		"\\bnet\\.minecraft\\.util\\.math\\.vector\\.Vector3d\\b", "net.minecraft.world.phys.Vec3")
	replace("\\bcom\\.mojang\\.math\\.Vector3f\\b", "net.minecraft.util.math.vector.Vector3f",
		"\\bnet\\.minecraft\\.util\\.math\\.vector\\.Vector3f\\b", "com.mojang.math.Vector3f")
	replace("\\bnet\\.minecraft\\.core\\.RegistryAccess\\b", "net.minecraft.util.registry.DynamicRegistries",
		"\\bnet\\.minecraft\\.util\\.registry\\.DynamicRegistries\\b", "net.minecraft.core.RegistryAccess")
	replace("\\bnet\\.minecraft\\.core\\.Registry\\b", "net.minecraft.util.registry.Registry",
		"\\bnet\\.minecraft\\.util\\.registry\\.Registry\\b", "net.minecraft.core.Registry")
	replace("\\bnet\\.minecraft\\.network\\.chat\\.TextColor\\b", "net.minecraft.util.text.Color",
		"\\bnet\\.minecraft\\.util\\.text\\.Color\\b", "net.minecraft.network.chat.TextColor")
	replace("\\bnet\\.minecraft\\.network\\.chat\\.MutableComponent\\b", "net.minecraft.util.text.IFormattableTextComponent",
		"\\bnet\\.minecraft\\.util\\.text\\.IFormattableTextComponent\\b", "net.minecraft.network.chat.MutableComponent")
	replace("\\bnet\\.minecraft\\.network\\.chat\\.Component\\b", "net.minecraft.util.text.ITextComponent",
		"\\bnet\\.minecraft\\.util\\.text\\.ITextComponent\\b", "net.minecraft.network.chat.Component")
	replace("\\bnet\\.minecraft\\.network\\.chat\\.TextComponent\\b", "net.minecraft.util.text.StringTextComponent",
		"\\bnet\\.minecraft\\.util\\.text\\.StringTextComponent\\b", "net.minecraft.network.chat.TextComponent")
	replace("\\bnet\\.minecraft\\.ChatFormatting\\b", "net.minecraft.util.text.TextFormatting",
		"\\bnet\\.minecraft\\.util\\.text\\.TextFormatting\\b", "net.minecraft.ChatFormatting")
	replace("\\bnet\\.minecraft\\.network\\.chat\\.TranslatableComponent\\b", "net.minecraft.util.text.TranslationTextComponent",
		"\\bnet\\.minecraft\\.util\\.text\\.TranslationTextComponent\\b", "net.minecraft.network.chat.TranslatableComponent")
	replace("\\bnet\\.minecraft\\.world\\.level\\.GameRules\\b", "net.minecraft.world.GameRules",
		"\\bnet\\.minecraft\\.world\\.GameRules\\b", "net.minecraft.world.level.GameRules")
	replace("\\bnet\\.minecraft\\.world\\.level\\.GameType\\b", "net.minecraft.world.GameType",
		"\\bnet\\.minecraft\\.world\\.GameType\\b", "net.minecraft.world.level.GameType")
	replace("\\bnet\\.minecraft\\.world\\.level\\.BlockAndTintGetter\\b", "net.minecraft.world.IBlockDisplayReader",
		"\\bnet\\.minecraft\\.world\\.IBlockDisplayReader\\b", "net.minecraft.world.level.BlockAndTintGetter")
	replace("\\bnet\\.minecraft\\.world\\.level\\.Level\\b", "net.minecraft.world.World",
		"\\bnet\\.minecraft\\.world\\.World\\b", "net.minecraft.world.level.Level")
	replace("\\bnet\\.minecraft\\.world\\.level\\.LevelSettings\\b", "net.minecraft.world.WorldSettings",
		"\\bnet\\.minecraft\\.world\\.WorldSettings\\b", "net.minecraft.world.level.LevelSettings")
	replace("\\bnet\\.minecraft\\.world\\.level\\.levelgen\\.WorldGenSettings\\b", "net.minecraft.world.gen.settings.DimensionGeneratorSettings",
		"\\bnet\\.minecraft\\.world\\.gen\\.settings\\.DimensionGeneratorSettings\\b", "net.minecraft.world.level.levelgen.WorldGenSettings")

	// mixin descriptors
	replace("Lcom/mojang/blaze3d/vertex/PoseStack;", "Lcom/mojang/blaze3d/matrix/MatrixStack;",
		"Lcom/mojang/blaze3d/matrix/MatrixStack;", "Lcom/mojang/blaze3d/vertex/PoseStack;")
	replace("Lnet/minecraft/client/renderer/MultiBufferSource;", "Lnet/minecraft/client/renderer/IRenderTypeBuffer;",
		"Lnet/minecraft/client/renderer/IRenderTypeBuffer;", "Lnet/minecraft/client/renderer/MultiBufferSource;")
	replace("Lnet/minecraft/client/renderer/blockentity/BlockEntityRenderer;", "Lnet/minecraft/client/renderer/tileentity/TileEntityRenderer;",
		"Lnet/minecraft/client/renderer/tileentity/TileEntityRenderer;", "Lnet/minecraft/client/renderer/blockentity/BlockEntityRenderer;")
	replace("Lnet/minecraft/world/level/block/entity/BlockEntity;", "Lnet/minecraft/tileentity/TileEntity;",
		"Lnet/minecraft/tileentity/TileEntity;", "Lnet/minecraft/world/level/block/entity/BlockEntity;")

	// nested classes
	replace("(?<![\\w.\$/])BlockBehaviour\\.BlockStateBase\\b", "AbstractBlock.AbstractBlockState",
		"(?<![\\w.\$/])AbstractBlock\\.AbstractBlockState\\b", "BlockBehaviour.BlockStateBase")
	replace("(?<![\\w.\$/])ChunkRenderDispatcher\\.RenderChunk\\b", "ChunkRenderDispatcher.ChunkRender",
		"(?<![\\w.\$/])ChunkRenderDispatcher\\.ChunkRender\\b", "ChunkRenderDispatcher.RenderChunk")
	replace("(?<![\\w.\$/])RegistryAccess\\.RegistryHolder\\b", "DynamicRegistries.Impl",
		"(?<![\\w.\$/])DynamicRegistries\\.Impl\\b", "RegistryAccess.RegistryHolder")
	replace("(?<![\\w.\$/])MultiBufferSource\\.BufferSource\\b", "IRenderTypeBuffer.Impl",
		"(?<![\\w.\$/])IRenderTypeBuffer\\.Impl\\b", "MultiBufferSource.BufferSource")
	replace("(?<![\\w.\$/])NativeImage\\.Format\\b", "NativeImage.PixelFormat",
		"(?<![\\w.\$/])NativeImage\\.PixelFormat\\b", "NativeImage.Format")

	// simple names
	replace("(?<![\\w.\$/])BlockBehaviour\\b(?!\\.BlockStateBase)", "AbstractBlock",
		"(?<![\\w.\$/])AbstractBlock\\b(?!\\.AbstractBlockState)", "BlockBehaviour")
	replace("(?<![\\w.\$/])Option\\b", "AbstractOption",
		"(?<![\\w.\$/])AbstractOption\\b", "Option")
	replace("(?<![\\w.\$/])ContainerObjectSelectionList\\b", "AbstractOptionList",
		"(?<![\\w.\$/])AbstractOptionList\\b", "ContainerObjectSelectionList")
	replace("(?<![\\w.\$/])SignBlock\\b", "AbstractSignBlock",
		"(?<![\\w.\$/])AbstractSignBlock\\b", "SignBlock")
	replace("(?<![\\w.\$/])Sheets\\b", "Atlases",
		"(?<![\\w.\$/])Atlases\\b", "Sheets")
	replace("(?<![\\w.\$/])BellBlockEntity\\b", "BellTileEntity",
		"(?<![\\w.\$/])BellTileEntity\\b", "BellBlockEntity")
	replace("(?<![\\w.\$/])WorldPreset\\b", "BiomeGeneratorTypeScreens",
		"(?<![\\w.\$/])BiomeGeneratorTypeScreens\\b", "WorldPreset")
	replace("(?<![\\w.\$/])RenderShape\\b", "BlockRenderType",
		"(?<![\\w.\$/])BlockRenderType\\b", "RenderShape")
	replace("(?<![\\w.\$/])ChestBlockEntity\\b", "ChestTileEntity",
		"(?<![\\w.\$/])ChestTileEntity\\b", "ChestBlockEntity")
	replace("(?<![\\w.\$/])ClientLevel\\b", "ClientWorld",
		"(?<![\\w.\$/])ClientWorld\\b", "ClientLevel")
	replace("(?<![\\w.\$/])TextColor\\b", "Color",
		"(?<![\\w.\$/])Color\\b", "TextColor")
	replace("(?<![\\w.\$/])CompoundTag\\b", "CompoundNBT",
		"(?<![\\w.\$/])CompoundNBT\\b", "CompoundTag")
	replace("(?<![\\w.\$/])DataPackConfig\\b", "DatapackCodec",
		"(?<![\\w.\$/])DatapackCodec\\b", "DataPackConfig")
	replace("(?<![\\w.\$/])CommonComponents\\b", "DialogTexts",
		"(?<![\\w.\$/])DialogTexts\\b", "CommonComponents")
	replace("(?<![\\w.\$/])WorldGenSettings\\b", "DimensionGeneratorSettings",
		"(?<![\\w.\$/])DimensionGeneratorSettings\\b", "WorldGenSettings")
	replace("(?<![\\w.\$/])RegistryAccess\\b(?!\\.RegistryHolder)", "DynamicRegistries",
		"(?<![\\w.\$/])DynamicRegistries\\b(?!\\.Impl)", "RegistryAccess")
	replace("(?<![\\w.\$/])SignEditScreen\\b", "EditSignScreen",
		"(?<![\\w.\$/])EditSignScreen\\b", "SignEditScreen")
	replace("(?<![\\w.\$/])EnderChestBlockEntity\\b", "EnderChestTileEntity",
		"(?<![\\w.\$/])EnderChestTileEntity\\b", "EnderChestBlockEntity")
	replace("(?<![\\w.\$/])Font\\b", "FontRenderer",
		"(?<![\\w.\$/])FontRenderer\\b", "Font")
	replace("(?<![\\w.\$/])Options\\b", "GameSettings",
		"(?<![\\w.\$/])GameSettings\\b", "Options")
	replace("(?<![\\w.\$/])ReloadInstance\\b", "IAsyncReloader",
		"(?<![\\w.\$/])IAsyncReloader\\b", "ReloadInstance")
	replace("(?<![\\w.\$/])BakedModel\\b", "IBakedModel",
		"(?<![\\w.\$/])IBakedModel\\b", "BakedModel")
	replace("(?<![\\w.\$/])BlockAndTintGetter\\b", "IBlockDisplayReader",
		"(?<![\\w.\$/])IBlockDisplayReader\\b", "BlockAndTintGetter")
	replace("(?<![\\w.\$/])LidBlockEntity\\b", "IChestLid",
		"(?<![\\w.\$/])IChestLid\\b", "LidBlockEntity")
	replace("(?<![\\w.\$/])MutableComponent\\b", "IFormattableTextComponent",
		"(?<![\\w.\$/])IFormattableTextComponent\\b", "MutableComponent")
	replace("(?<![\\w.\$/])PreparableReloadListener\\b", "IFutureReloadListener",
		"(?<![\\w.\$/])IFutureReloadListener\\b", "PreparableReloadListener")
	replace("(?<![\\w.\$/])GuiEventListener\\b", "IGuiEventListener",
		"(?<![\\w.\$/])IGuiEventListener\\b", "GuiEventListener")
	replace("(?<![\\w.\$/])MetadataSectionSerializer\\b", "IMetadataSectionSerializer",
		"(?<![\\w.\$/])IMetadataSectionSerializer\\b", "MetadataSectionSerializer")
	replace("(?<![\\w.\$/])ModelState\\b", "IModelTransform",
		"(?<![\\w.\$/])IModelTransform\\b", "ModelState")
	replace("(?<![\\w.\$/])PackSource\\b", "IPackNameDecorator",
		"(?<![\\w.\$/])IPackNameDecorator\\b", "PackSource")
	replace("(?<![\\w.\$/])MultiBufferSource\\b(?!\\.BufferSource)", "IRenderTypeBuffer",
		"(?<![\\w.\$/])IRenderTypeBuffer\\b(?!\\.Impl)", "MultiBufferSource")
	replace("(?<![\\w.\$/])FormattedCharSequence\\b", "IReorderingProcessor",
		"(?<![\\w.\$/])IReorderingProcessor\\b", "FormattedCharSequence")
	replace("(?<![\\w.\$/])ResourceManager\\b", "IResourceManager",
		"(?<![\\w.\$/])IResourceManager\\b", "ResourceManager")
	replace("(?<![\\w.\$/])PackResources\\b", "IResourcePack",
		"(?<![\\w.\$/])IResourcePack\\b", "PackResources")
	replace("(?<![\\w.\$/])Component\\b", "ITextComponent",
		"(?<![\\w.\$/])ITextComponent\\b", "Component")
	replace("(?<![\\w.\$/])UnbakedModel\\b", "IUnbakedModel",
		"(?<![\\w.\$/])IUnbakedModel\\b", "UnbakedModel")
	replace("(?<![\\w.\$/])VertexConsumer\\b", "IVertexBuilder",
		"(?<![\\w.\$/])IVertexBuilder\\b", "VertexConsumer")
	replace("(?<![\\w.\$/])ItemTransforms\\b", "ItemCameraTransforms",
		"(?<![\\w.\$/])ItemCameraTransforms\\b", "ItemTransforms")
	replace("(?<![\\w.\$/])ItemProperties\\b", "ItemModelsProperties",
		"(?<![\\w.\$/])ItemModelsProperties\\b", "ItemProperties")
	replace("(?<![\\w.\$/])ItemOverrides\\b", "ItemOverrideList",
		"(?<![\\w.\$/])ItemOverrideList\\b", "ItemOverrides")
	replace("(?<![\\w.\$/])BlockEntityWithoutLevelRenderer\\b", "ItemStackTileEntityRenderer",
		"(?<![\\w.\$/])ItemStackTileEntityRenderer\\b", "BlockEntityWithoutLevelRenderer")
	replace("(?<![\\w.\$/])Mth\\b", "MathHelper",
		"(?<![\\w.\$/])MathHelper\\b", "Mth")
	replace("(?<![\\w.\$/])PoseStack\\b", "MatrixStack",
		"(?<![\\w.\$/])MatrixStack\\b", "PoseStack")
	replace("(?<![\\w.\$/])BlockModelRotation\\b", "ModelRotation",
		"(?<![\\w.\$/])ModelRotation\\b", "BlockModelRotation")
	replace("(?<![\\w.\$/])OptionsList\\b", "OptionsRowList",
		"(?<![\\w.\$/])OptionsRowList\\b", "OptionsList")
	replace("(?<![\\w.\$/])ResourceKey\\b", "RegistryKey",
		"(?<![\\w.\$/])RegistryKey\\b", "ResourceKey")
	replace("(?<![\\w.\$/])Lighting\\b", "RenderHelper",
		"(?<![\\w.\$/])RenderHelper\\b", "Lighting")
	replace("(?<![\\w.\$/])Material\\b", "RenderMaterial",
		"(?<![\\w.\$/])RenderMaterial\\b", "Material")
	replace("(?<![\\w.\$/])ItemBlockRenderTypes\\b", "RenderTypeLookup",
		"(?<![\\w.\$/])RenderTypeLookup\\b", "ItemBlockRenderTypes")
	replace("(?<![\\w.\$/])PackType\\b", "ResourcePackType",
		"(?<![\\w.\$/])ResourcePackType\\b", "PackType")
	replace("(?<![\\w.\$/])OptionsSubScreen\\b", "SettingsScreen",
		"(?<![\\w.\$/])SettingsScreen\\b", "OptionsSubScreen")
	replace("(?<![\\w.\$/])ShulkerBoxBlockEntity\\b", "ShulkerBoxTileEntity",
		"(?<![\\w.\$/])ShulkerBoxTileEntity\\b", "ShulkerBoxBlockEntity")
	replace("(?<![\\w.\$/])SignBlockEntity\\b", "SignTileEntity",
		"(?<![\\w.\$/])SignTileEntity\\b", "SignBlockEntity")
	replace("(?<![\\w.\$/])SignRenderer\\b", "SignTileEntityRenderer",
		"(?<![\\w.\$/])SignTileEntityRenderer\\b", "SignRenderer")
	replace("(?<![\\w.\$/])TextComponent\\b", "StringTextComponent",
		"(?<![\\w.\$/])StringTextComponent\\b", "TextComponent")
	replace("(?<![\\w.\$/])ChatFormatting\\b", "TextFormatting",
		"(?<![\\w.\$/])TextFormatting\\b", "ChatFormatting")
	replace("(?<![\\w.\$/])BlockEntity\\b", "TileEntity",
		"(?<![\\w.\$/])TileEntity\\b", "BlockEntity")
	replace("(?<![\\w.\$/])BlockEntityRenderer\\b", "TileEntityRenderer",
		"(?<![\\w.\$/])TileEntityRenderer\\b", "BlockEntityRenderer")
	replace("(?<![\\w.\$/])BlockEntityRenderDispatcher\\b", "TileEntityRendererDispatcher",
		"(?<![\\w.\$/])TileEntityRendererDispatcher\\b", "BlockEntityRenderDispatcher")
	replace("(?<![\\w.\$/])BlockEntityType\\b", "TileEntityType",
		"(?<![\\w.\$/])TileEntityType\\b", "BlockEntityType")
	replace("(?<![\\w.\$/])TranslatableComponent\\b", "TranslationTextComponent",
		"(?<![\\w.\$/])TranslationTextComponent\\b", "TranslatableComponent")
	replace("(?<![\\w.\$/])VanillaPackResources\\b", "VanillaPack",
		"(?<![\\w.\$/])VanillaPack\\b", "VanillaPackResources")
	replace("(?<![\\w.\$/])Vec3\\b", "Vector3d",
		"(?<![\\w.\$/])Vector3d\\b", "Vec3")
	replace("(?<![\\w.\$/])AbstractWidget\\b", "Widget",
		"(?<![\\w.\$/])Widget\\b", "AbstractWidget")
	replace("(?<![\\w.\$/])Level\\b", "World",
		"(?<![\\w.\$/])World\\b", "Level")
	replace("(?<![\\w.\$/])LevelRenderer\\b", "WorldRenderer",
		"(?<![\\w.\$/])WorldRenderer\\b", "LevelRenderer")
	replace("(?<![\\w.\$/])LevelSettings\\b", "WorldSettings",
		"(?<![\\w.\$/])WorldSettings\\b", "LevelSettings")
}
